# CRMEB 相关配置
crmeb:
  version: CRMEB-JAVA-ET-v1.1 # 当前代码版本
  domain: #配合swagger使用 # 待部署域名
  asyncConfig: false #是否同步config表数据到redis
  imagePath: /www/wwwroot/你的本地素材路径 也就是crmebimage文件夹路径/ # 服务器图片路径配置 斜杠结尾
  captchaOn: false # 是否开启行为验证码
  paypalBrandName: Crmeb Java
  paypalReturnUri: http://H5域名地址/pages/order_pay_status/index
  paypalPcReturnUri: http://pc域名地址/order/payment_result

server:
  port: 20008
  servlet:
    context-path: /         # 访问path
  tomcat:
      uri-encoding: UTF-8     # 默认编码格式
      max-threads: 1000       # 最大线程数量 默认200
      min-spare-threads: 30   # 初始化启动线程数量

spring:
  profiles:
    #  配置的环境
    active: beta
  servlet:
    multipart:
      max-file-size: 50MB #设置单个文件大小
      max-request-size: 50MB #设置单次请求文件的总大小
    #  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.0:3306/java_et?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
    username: java_et
    password: 111111
  redis:
    host: 127.0.0.1 #地址
    port: 6379 #端口
    password: 111111
    timeout: 10000 # 连接超时时间（毫秒）
    database: 7 #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
