# CRMEB 相关配置
crmeb:
  version: CRMEB-JAVA-ET-v1.1 # 当前代码版本
  imagePath: /www/wwwroot/admin.api.et.crmeb.xbdzz.cn/ # 服务器图片路径配置 斜杠结尾
  asyncConfig: false #是否同步config表数据到redis
  paypalBrandName: Crmeb Java
  paypalReturnUri: http://H5域名地址/pages/order_pay_status/index
  paypalPcReturnUri: http://pc域名地址/order/payment_result

server:
  port: 20210

spring:
  profiles:
    #  配置的环境
    active: trip
    #  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java_et_trip?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
    username: java_et_trip
    password: 111111
  redis:
    host: 127.0.0.1 #地址
    port: 6379 #端口
    password: 111111
    timeout: 10000 # 连接超时时间（毫秒）
    database: 1 #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1

debug: true
logging:
  level:
    io.swagger.*: error
    com.zbjk.crmeb: debug
    org.springframework.boot.autoconfigure: ERROR
  config: classpath:logback-spring.xml
  file:
    path: ./crmeb_log

# mybatis 配置
mybatis-plus:
  # 配置slq打印日志
  configuration:
    log-impl:

#swagger 配置
swagger:
  basic:
    enable: true #是否开启界面
    check: true #是否打开验证
    username: crmeb #访问swagger的账号
    password: crmeb.com #访问swagger的密码
